### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable with PHP 7.3 and module graphite v1.1.0

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icingaweb2-module-graphite#248]
Hi,
we have a problem similar to issue #168, but we're using PHP 7.3 and module-graphite v1.1.0 on RHEL7.8

## Expected Behavior
Performance history should be displayed in Icingaweb2

## Current Behavior
No graphs are shown, only the message:
count(): Parameter must be an array or an object that implements Countable

## Steps to Reproduce (for bugs)

1. Install Icingaweb2 + this module
2. Login to the web interface
3. Navigate to a host or service that provides perfdata
4. Instead of the graphs, you will see the above error

(Note: the Graphs section also shows up on hosts/services that don't provide any performance data, with the same error.)

## Context
We are trying to test a new Graphite system

## Your Environment
````
  [root@xxxxmo12 ~]# cat /etc/redhat-release 
  Red Hat Enterprise Linux Server release 7.8 (Maipo)
  [root@xxxxxmo12 ~]# icingacli version
  Icinga Web 2  2.8.2     
  Git Commit    8a89839af94a247ee2149b2336c73b8251b477c0 
  PHP Version   7.3.11    
  MODULE           VERSION   
  setup            2.8.2     
  <redacted>umleitung     0.0.0     (own module)
  businessprocess  2.2.0     
  director         1.7.2     
  doc              2.8.2     
  elasticsearch    1.0.0     
  fileshipper      1.1.0     
  globe            1.0.4     
  graphite         1.1.0     
  incubator        0.5.0     
  ipl              v0.5.0    
  mapDatatype      0.1.0     
  monitoring       2.8.2     
  reactbundle      0.7.0     
  translation      2.8.2     
  vsphere          1.1.0     
  vspheredb        1.1.0
````

We've also tried using a fresh clone from the repository, but no change:

![grafik](https://user-images.githubusercontent.com/23358770/94678840-6ea35700-031f-11eb-8c04-23d4feb52959.png)

**Comment by Al2Klimov** [comment]
Hello @akqopensystems and thank you for reporting!

Please could you provide a screenshot showing the problem?

Best,
AK

**Comment by akqopensystems** [comment]
Hi, here's the screenshot:

![grafik](https://user-images.githubusercontent.com/23358770/94680272-c773ef00-0321-11eb-9931-83fbc72475f8.png)

**Comment by Al2Klimov** [comment]
Please apply the following patch and paste the result here.

```patch
diff --git library/Graphite/Web/Widget/Graphs.php library/Graphite/Web/Widget/Graphs.php
index 25871ec..da286f1 100644
--- library/Graphite/Web/Widget/Graphs.php
+++ library/Graphite/Web/Widget/Graphs.php
@@ -2,10 +2,12 @@

 namespace Icinga\Module\Graphite\Web\Widget;

+use Exception;
 use Icinga\Application\Config;
 use Icinga\Application\Icinga;
 use Icinga\Authentication\Auth;
 use Icinga\Exception\ConfigurationError;
+use Icinga\Exception\IcingaException;
 use Icinga\Module\Graphite\Forms\TimeRangePicker\TimeRangePickerTrait;
 use Icinga\Module\Graphite\Graphing\Chart;
 use Icinga\Module\Graphite\Graphing\GraphingTrait;
@@ -389,6 +391,8 @@ abstract class Graphs extends AbstractWidget
                         )
                         : ['', '']
                 ) . '</p>';
+        } catch (Exception $e) {
+            return IcingaException::getConfidentialTraceAsString($e);
         }

         $view = $this->view();
```

**Comment by akqopensystems** [comment]
Hi,

we've patched the code and now we're getting the following stack trace:
````
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array) #1 /usr/share/icingaweb2/modules/elasticsearch/library/vendor/iplx/Http/Client.php(180): count(NULL)
#2 /usr/share/icingaweb2/modules/elasticsearch/library/vendor/iplx/Http/Client.php(195): iplx\Http\Client->executeHandle(Object(iplx\Http\Handle))
#3 /usr/share/icingaweb2/modules/graphite/library/Graphite/Graphing/GraphiteWebClient.php(83): iplx\Http\Client->send(Object(iplx\Http\Request), Array)
#4 /usr/share/icingaweb2/modules/graphite/library/Graphite/Graphing/MetricsQuery.php(147): Icinga\Module\Graphite\Graphing\GraphiteWebClient->request(Object(Icinga\Web\Url))
#5 /usr/share/icingaweb2/modules/graphite/library/Graphite/Graphing/Template.php(88): Icinga\Module\Graphite\Graphing\MetricsQuery->fetchColumn()
#6 /usr/share/icingaweb2/modules/graphite/library/Graphite/Web/Widget/Graphs.php(246): Icinga\Module\Graphite\Graphing\Template->getCharts(Object(Icinga\Module\Graphite\Graphing\MetricsDataSource), Object(Icinga\Module\Monitoring\Object\Host), Array, Array)
#7 /usr/share/icingaweb2/modules/graphite/library/Graphite/Web/Widget/Graphs.php(380): Icinga\Module\Graphite\Web\Widget\Graphs->getGraphsList()
#8 /usr/share/php/Icinga/Web/Widget/AbstractWidget.php(114): Icinga\Module\Graphite\Web\Widget\Graphs->render(Object(Icinga\Web\View))
#9 /usr/share/icingaweb2/modules/graphite/library/Graphite/ProvidedHook/Monitoring/DetailviewExtension.php(28): Icinga\Web\Widget\AbstractWidget->__toString()
#10 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(98): Icinga\Module\Graphite\ProvidedHook\Monitoring\DetailviewExtension->getHtmlForObject(Object(Icinga\Module\Monitoring\Object\Host))
#11 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostController.php(63): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HostController->showAction()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#18 {main}
````

**Comment by Al2Klimov** [comment]
> #0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array) #1 /usr/share/icingaweb2/modules/elasticsearch/library/vendor/iplx/Http/Client.php(180): count(NULL)

Please update your elasticsearch module to master and try again.

**Comment by akqopensystems** [comment]
For the moment, we've deactivated the elasticsearch module and graphite is working now.
Thanks!
