### ISSUE TITLE
Icingaweb2 displaying graphs only after "inspect" in webbrowser. Possible Javascript error?

### ISSUE THREAD

**Issue by alamp1360** [Icinga/icingaweb2-module-graphite#290]
I'm facing an issue with icingaweb2 and the graphite module:
The preloadDummy 1x1px image is shown and is not getting replaced with the actual graph.

If i open the "debugging console" of the webbrowser (right click and selecting "inspect" from the menu), the graph suddenly appears.
Browser is Google Chrome version 105.0.5195.125 on a Windows machine.

In the Console, i see the following error messages appear every few seconds:

icinga.min.js:733 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '> tbody > tr' is not a valid selector.
    at Collapsible.canCollapse (https://monitor.b99banking.internal/js/icinga.min.js:733:20)
    at https://monitor.b99banking.internal/js/icinga.min.js:711:188
    at NodeList.forEach (<anonymous>)
    at HTMLDivElement.onRendered (https://monitor.b99banking.internal/js/icinga.min.js:711:117)
    at HTMLDocument.dispatch (https://monitor.b99banking.internal/js/icinga.min.js:19:43064)
    at v.handle (https://monitor.b99banking.internal/js/icinga.min.js:19:41048)
    at Object.trigger (https://monitor.b99banking.internal/js/icinga.min.js:19:71515)
    at HTMLDivElement.<anonymous> (https://monitor.b99banking.internal/js/icinga.min.js:19:72110)
    at Function.each (https://monitor.b99banking.internal/js/icinga.min.js:19:3003)
    at S.fn.init.each (https://monitor.b99banking.internal/js/icinga.min.js:19:1481)

If i change the file /usr/share/icingaweb2/modules/graphite/library/Graphite/Web/Widget/Graphs.php, line 633 from
    public function setPreloadDummy($preloadDummy = true)
to
    public function setPreloadDummy($preloadDummy = false)
then the graph gets displayed immediately, but looks really ugly. I guess it is somehow expanded too far.

My best guess about the issue is some kind of JavaScript problem....

My setup:
RedHat 8.0 with Docker containers using all the latest Icinga "Master" images.
Icingaweb 2.11.1
PHP 7.4.30
IcingaDB 1.0.1
graphite 1.2.1

Please help!
Greetings

**Comment by nilmerg** [comment]
That's a (fixed) bug in the master of Icinga Web. Update the docker image.

**Comment by alamp1360** [comment]
I did the update on IcingaWeb2. Now the graphs are being displayed. That Javascript error is also gone.
Thanks a lot for the fast reaction!
