### ISSUE TITLE
Error: Call to protected method Icinga\Application\ClassLoader::classBelongsToModule()

### ISSUE THREAD

**Issue by devent** [Icinga/icingaweb2-module-graphite#73]
Iciangaweb2 with Graphite module from git master. Trying to see graph for a service. See the screenshot.

![grafik](https://user-images.githubusercontent.com/82924/32004354-de0908e4-b9a1-11e7-8480-1395bc3d8beb.png)

```
Stacktrace ...
Fatal error: Uncaught Error: Call to protected method Icinga\Application\ClassLoader::classBelongsToModule() from context 'Icinga\Module\Monitoring\Hook\DetailviewExtensionHook' in /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/DetailviewExtensionHook.php:91 Stack trace: #0 /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(88): Icinga\Module\Monitoring\Hook\DetailviewExtensionHook->getModule() #1 /usr/local/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(66): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction() #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->showAction() #3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction') #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Ici in /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/DetailviewExtensionHook.php on line 91
```

## Your Environment

Icingaweb2

```
ARG GITREF_ICINGAWEB2=master
    && mkdir -p /usr/local/share/icingaweb2/modules/ \
    && wget -q --no-cookies -O - "https://github.com/Icinga/icingaweb2/archive/${GITREF_ICINGAWEB2}.tar.gz" \
    | tar xz --strip-components=2 --directory=/usr/local/share/icingaweb2/modules -f - icingaweb2-${GITREF_ICINGAWEB2}/modules/monitoring icingaweb2-${GITREF_ICINGAWEB2}/modules/doc
```

Graphite Module

```
ARG GITREF_MODGRAPHITE=master
# Icingaweb2 Graphite
    && mkdir -p /usr/local/share/icingaweb2/modules/graphite \
    && wget -q --no-cookies -O - "https://github.com/Icinga/icingaweb2-module-graphite/archive/${GITREF_MODGRAPHITE}.tar.gz" \
    | tar xz --strip-components=1 --directory=/usr/local/share/icingaweb2/modules/graphite -f - icingaweb2-module-graphite-${GITREF_MODGRAPHITE}/ \
    && cp -r /usr/local/share/icingaweb2/modules/graphite/templates/ /etc/icingaweb2/modules/graphite
```

* Module version (System - About):

```
www-data@d88c1ffe4108:/$ uname -a
Linux d88c1ffe4108 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
```

* Icinga Web 2 version and modules (System - About):

```
Version
    2.4.2
Copyright
    © 2013-2017 The Icinga Project 

Loaded modules
Name 	Version
director 	master
doc 	2.4.2
graphite 	0.0.0
monitoring 	2.4.2 
```

* Icinga 2 version (`icinga2 --version`):

```
nagios@afa85c8cad58:/$ icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 3.16.0-4-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: f42b8d72881d
```

* Webserver, PHP versions:

```
nagios@afa85c8cad58:/$ php --version
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by devent** [comment]
The issue is fixed in the master branch of Icingaweb2. In the commit: https://github.com/Icinga/icingaweb2/commit/c2ee3bef0644e372a5e1f781511b88f130f07599#diff-ff1d33ac6cee9f2bacaade66db892d59
