### ISSUE TITLE
Error at startup : syntax error, unexpected '!' in Unknown on line 5

### ISSUE THREAD

**Issue by Isma399** [Icinga/icingaweb2-module-graphite#96]
Just after copying the module in /usr/share/icingaweb2/modules/graphite then enable it, configure Backend raises this error:
**syntax error, unexpected '!' in Unknown on line 5**
<pre>
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'syntax error, u...', '/usr/share/php/...', 263, Array)
#1 /usr/share/php/Icinga/File/Ini/IniParser.php(263): parse_ini_string('[graphite]\nlega...', true)
#2 /usr/share/php/Icinga/Application/Config.php(326): Icinga\File\Ini\IniParser::parseIniFile('/etc/icingaweb2...')
#3 /usr/share/php/Icinga/Application/Config.php(421): Icinga\Application\Config::fromIni('/etc/icingaweb2...')
#4 /usr/share/php/Icinga/Web/Controller/ModuleActionController.php(46): Icinga\Application\Config::module('graphite')
#5 /usr/share/icingaweb2/modules/graphite/application/controllers/ConfigController.php(20): Icinga\Web\Controller\ModuleActionController->Config()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Graphite\Controllers\ConfigController->backendAction()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('backendAction')
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#12 {main}
</pre>

## Your Environment

* Module version (System - About): 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): v2.6.2
* Operating System and version: CentOS  7.3.1611 
* Webserver, PHP versions: Apache 2.4 et Php 7.0.25 

Thanks for your help

**Comment by Isma399** [comment]
Sorry, the problem was cause with the update to IcingaWeb 2.5.
